# Generated by Django 3.1.7 on 2021-04-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
        migrations.AddField(
            model_name='person',
            name='sort_name',
            field=models.CharField(help_text='Input the name as it should be sorted. (e.g. "Mercury, Freddie")', max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='sort_name_ar',
            field=models.CharField(help_text='Input the name as it should be sorted. (e.g. "Mercury, Freddie")', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='sort_name_en',
            field=models.CharField(help_text='Input the name as it should be sorted. (e.g. "Mercury, Freddie")', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='sort_name_he',
            field=models.CharField(help_text='Input the name as it should be sorted. (e.g. "Mercury, Freddie")', max_length=255, null=True),
        ),
    ]
