# Generated by Django 3.1.3 on 2020-11-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'person', 'verbose_name_plural': 'people'},
        ),
        migrations.AlterModelOptions(
            name='profession',
            options={'verbose_name': 'profession', 'verbose_name_plural': 'professions'},
        ),
        migrations.AddField(
            model_name='person',
            name='name_ar',
            field=models.CharField(help_text='Full name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_en',
            field=models.CharField(help_text='Full name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name_he',
            field=models.CharField(help_text='Full name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profession',
            name='title_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profession',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profession',
            name='title_he',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(help_text='Full name', max_length=100),
        ),
    ]
