# Generated by Django 3.1.3 on 2020-11-18 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_profession_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('-name',), 'verbose_name_plural': 'people'},
        ),
        migrations.AlterModelOptions(
            name='profession',
            options={'ordering': ('-title',)},
        ),
    ]
