# Generated by Django 3.1.3 on 2020-11-18 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.profession'),
        ),
    ]
