version: 2
snapshot:
  widths:
    - 320
    - 1440
  minHeight: 1024
discovery:
  allowedHostnames: ["unpkg.com"]
  networkIdleTimeout: 100
static:
  baseUrl: /
  include: "**/*.{html,htm}"
  exclude: ""
upload:
  files: "**/*.{png,jpg,jpeg}"
  ignore: ""
