version: 2
snapshot:
  widths:
    - 320
    - 1440
  minHeight: 1024
discovery:
  allowedHostnames:
    [
      "unpkg.com",
      "cdnjs.cloudflare.com",
      "princeton.edu",
      "arks.princeton.edu",
      "figgy.princeton.edu",
      "iiif-cloud.princeton.edu",
    ]
  networkIdleTimeout: 500
static:
  baseUrl: /
  include: "**/*.{html,htm}"
  exclude: ""
upload:
  files: "**/*.{png,jpg,jpeg}"
  ignore: ""
