---
# Crowdin localization configuration; see:
# https://support.crowdin.com/configuration-file/

commit_message: "[ci skip]"
files:
  - source: geniza/locale/en/LC_MESSAGES/django.po
    translation: geniza/locale/%two_letters_code%/LC_MESSAGES/django.po
