[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "geniza"
description = "Cairo Geniza - Python/Django web application"
requires-python = ">=3.9"
license = { text = "Apache-2" }
classifiers = ["Programming Language :: Python :: 3"]
dependencies = [
    "django>=3.2,<4.0",
    "psycopg2-binary",
    "pucas>=0.6",
    "django-split-settings",
    "requests",
    "django-taggit>=1.5.1,<2.0",
    # TODO: unpin piffle from 0.4 once breaking changes with piffle.iiif are handled
    "piffle==0.4",
    "taggit-selectize",
    # NOTE: as of 2024-07-91, django-multiselectfield 0.1.13 causes an error in unit"
    # tests and loaddata for loading fixtures"
    "django-multiselectfield==0.1.12",
    # NOTE: as of 2022-04-29, modeltranslation v0.17.6 causes an error in Django admin
    # TypeError: Cannot use multi-field values as a filter value.
    "django-modeltranslation==0.17.5",
    "django-admin-sortable2",
    "python-dateutil>=2.8",
    "django-tabular-export",
    "parasolr>=0.9.1",
    "django-gfklookupwidget",
    "django-adminlogentries",
    "django-autocomplete-light>=3.11.0",
    "django-webpack-loader",
    "django-csp",
    "gitpython",
    "eulxml",
    "rich",
    "wagtail>=2.15.3,<2.16",
    "wagtail-localize",
    "rdflib<6.2",
    "djiffy>=0.8",
    "natsort",
    "django-widget-tweaks",
    "django-csp-helpers",
    "django-fullurl",
    "django-admin-inline-paginator",
    "convertdate",
    "unidecode",
    "addict",
    "beautifulsoup4",
    "bleach",
    "python-slugify"
]
dynamic = ["version", "readme"]

[tool.setuptools]
packages = ["geniza"]

[tool.setuptools.dynamic]
version = { attr = "geniza.__version__" }
readme = { file = ["README.rst"] }

[project.optional-dependencies]
dev = [
    "sphinx",
    "pytest>=4.6",# required for pytest-cov
    "pytest-django>=4.1.0,<4.5.0",
    "pytest-cov",
    "pytest-order",
    "wheel",
    "django-dbml==0.7.0",
    "percy-selenium>=2.1.1",
    "selenium>=4.8.0",
    "django-fixture-magic",
    "future",
    "google-api-python-client",
    "google_auth_oauthlib",
    "django-debug-toolbar",
    "pre-commit",
    "black"
]
test = [
    "pytest>=4.6",# required for pytest-cov
    "pytest-django>=4.1.0,<4.5.0",
    "pytest-cov",
    "pytest-order",
    "wheel",
    "django-dbml==0.7.0",
    "percy-selenium>=2.1.1",
    "selenium>=4.8.0",
    "django-fixture-magic"
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "geniza.settings"
# look for tests in standard django test location
python_files = ["geniza/**/tests.py", "geniza/**/tests/*.py"]
testpaths = "geniza"
markers = ["last", "second_to_last"]


[tool.black]
line-length = 88
target-version = ['py39']
# include = ''
# extend-exclude = ''