# Generated by Django 3.1.6 on 2021-02-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255)),
                ('script', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255, help_text='Option to override the autogenerated language-script name', null=True, unique=True))
            ],
            options={
                'ordering': ['language'],
            }
        ),
        migrations.AddConstraint(
            model_name='languagescript',
            constraint=models.UniqueConstraint(fields=('language', 'script'), name='unique_language_script'),
        ),
        migrations.AlterModelOptions(
            name='library',
            options={'ordering': ['name'], 'verbose_name_plural': 'Libraries'},
        )
    ]
