# Generated by Django 3.1.6 on 2021-02-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255)),
                ('script', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True, unique=True))
            ],
            options={
                'ordering': ['language'],
            }
        )
    ]
