# Generated by Django 3.1.6 on 2021-03-02 15:53

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0003_taggeditem_add_unique_index"),
        ("corpus", "0001_create_collection_languagescript"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="PGPID"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "old_input_by",
                    models.CharField(
                        help_text="Legacy input information from Google Sheets",
                        max_length=255,
                        verbose_name="Legacy input by",
                    ),
                ),
                (
                    "old_input_date",
                    models.CharField(
                        help_text="Legacy input date from Google Sheets",
                        max_length=255,
                        verbose_name="Legacy input date",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "language_note",
                    models.TextField(
                        blank=True, help_text="Notes on diacritics, vocalisation, etc."
                    ),
                ),
            ],
            options={
                "ordering": ["fragments__shelfmark"],
            },
        ),
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Fragment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shelfmark", models.CharField(max_length=255, unique=True)),
                (
                    "old_shelfmarks",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Historical Shelfmarks"
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Link to library catalog record for this fragment.",
                        verbose_name="URL",
                    ),
                ),
                ("iiif_url", models.URLField(blank=True, verbose_name="IIIF URL")),
                ("multifragment", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="corpus.collection",
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="languagescript",
            options={
                "ordering": ["language"],
                "verbose_name": "Language + Script",
                "verbose_name_plural": "Languages + Scripts",
            },
        ),
        migrations.CreateModel(
            name="TextBlock",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("r", "recto"),
                            ("v", "verso"),
                            ("rv", "recto and verso"),
                        ],
                        max_length=5,
                    ),
                ),
                ("extent_label", models.CharField(blank=True, max_length=255)),
                (
                    "order",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Order if there are multiple fragments. Top to bottom or right to left.",
                        null=True,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="corpus.document",
                    ),
                ),
                (
                    "fragment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="corpus.fragment",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AlterModelOptions(
            name="textblock",
            options={"ordering": ["order"], "verbose_name": "Related Fragment"},
        ),
        migrations.AddField(
            model_name="document",
            name="doctype",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="corpus.documenttype",
                verbose_name="Type",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="fragments",
            field=models.ManyToManyField(
                through="corpus.TextBlock", to="corpus.Fragment"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="languages",
            field=models.ManyToManyField(blank=True, to="corpus.LanguageScript"),
        ),
        migrations.AddField(
            model_name="document",
            name="probable_languages",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to=models.Q(_negated=True, language="Unknown"),
                related_name="probable_document",
                to="corpus.LanguageScript",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
                blank=True,
            ),
        ),
    ]
