# Generated by Django 3.1.7 on 2021-03-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpus", "0005_add_suppressed_docs"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="needs_review",
            field=models.TextField(
                blank=True,
                help_text="Enter text here if an administrator needs to review this document.",
            ),
        ),
    ]
