# Generated by Django 3.1.7 on 2021-03-16 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpus", "0006_document_needs_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="fragment",
            name="needs_review",
            field=models.TextField(
                blank=True,
                help_text="Enter text here if an administrator needs to review this fragment.",
            ),
        ),
    ]
