# Generated by Django 3.1.6 on 2021-04-07 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("corpus", "0009_document_ordering_collection_meta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="old_input_by",
        ),
        migrations.RemoveField(
            model_name="document",
            name="old_input_date",
        ),
    ]
