# Generated by Django 3.1 on 2021-05-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpus", "0012_region_subfragment"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="old_pgpid",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
