# Generated by Django 3.1 on 2021-08-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpus", "0015_add_document_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="document",
            old_name="probable_languages",
            new_name="secondary_languages",
        ),
        migrations.AlterField(
            model_name="document",
            name="languages",
            field=models.ManyToManyField(
                blank=True, to="corpus.LanguageScript", verbose_name="Primary Languages"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="secondary_languages",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to=models.Q(_negated=True, language__exact="Unknown"),
                related_name="secondary_document",
                to="corpus.LanguageScript",
            ),
        ),
    ]
