# Generated by Django 3.1 on 2021-08-19 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpus", "0017_secondary_lang_allow_unknown"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="doctype",
            field=models.ForeignKey(
                blank=True,
                help_text='Refer to <a href="https://docs.google.com/document/d/1FHr1iS_JD5h-y5O1rv5JNNw1OqEVQFb-vSTGr3hoiF4/edit" target="_blank">PGP Document Type Guide</a>',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="corpus.documenttype",
                verbose_name="Type",
            ),
        ),
    ]
