# Generated by Django 3.2.8 on 2021-10-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpus", "0018_document_doctype_help_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="documenttype",
            name="display_label",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
