# Generated by Django 3.2.8 on 2021-10-25 13:41

from django.db import migrations


def populate_document_types(apps, schema_editor):
    DocumentType = apps.get_model("corpus", "DocumentType")
    types = [
        {
            "name": "Legal",
            "display_label": "Legal document",
        },
        {
            "name": "Literary",
            "display_label": "Literary text",
        },
        {
            "name": "Paraliterary",
            "display_label": "Paraliterary text",
        },
        {
            "name": "State",
            "display_label": "State document",
        },
    ]
    for type in types:
        DocumentType.objects.update_or_create(
            name=type["name"], defaults={"display_label": type["display_label"]}
        )


class Migration(migrations.Migration):

    dependencies = [
        ("corpus", "0019_documenttype_display_label"),
    ]

    operations = [
        migrations.RunPython(populate_document_types),
    ]
