# Generated by Django 3.2.8 on 2021-10-25 13:41

from django.db import migrations


def populate_document_types(apps, schema_editor):
    DocumentType = apps.get_model("corpus", "DocumentType")
    DocumentType.objects.update_or_create(
        name="Legal", defaults={"display_label": "Legal document"}
    )
    DocumentType.objects.update_or_create(
        name="Letter", defaults={"display_label": "Letter"}
    )
    DocumentType.objects.update_or_create(
        name="List or table", defaults={"display_label": "List or table"}
    )
    DocumentType.objects.update_or_create(
        name="Literary", defaults={"display_label": "Literary text"}
    )
    DocumentType.objects.update_or_create(
        name="Paraliterary", defaults={"display_label": "Paraliterary text"}
    )
    DocumentType.objects.update_or_create(
        name="State", defaults={"display_label": "State document"}
    )
    DocumentType.objects.update_or_create(
        name="Unknown", defaults={"display_label": "Unknown type"}
    )


class Migration(migrations.Migration):

    dependencies = [
        ("corpus", "0019_documenttype_display_label"),
    ]

    operations = [
        migrations.RunPython(populate_document_types),
    ]
