# Generated by Django 3.2.6 on 2021-11-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpus", "0020_populate_documenttype_display_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="languagescript",
            name="iso_code",
            field=models.CharField(
                blank=True,
                help_text="ISO 639 code for this language (2 or 3 letters)",
                max_length=3,
                verbose_name="ISO Code",
            ),
        ),
    ]
