# Generated by Django 3.2.8 on 2021-11-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpus", "0020_populate_documenttype_display_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documenttype",
            name="display_label",
            field=models.CharField(
                blank=True,
                help_text="Optional label for display on the public site",
                max_length=255,
            ),
        ),
    ]
