# Generated by Django 3.2.8 on 2021-11-29 21:10

import taggit_selectize.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0003_taggeditem_add_unique_index"),
        ("corpus", "0020_populate_documenttype_display_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="tags",
            field=taggit_selectize.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                related_name="tagged_document",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
