# Generated by Django 3.2.6 on 2021-11-29 17:14

from django.db import migrations


def populate_language_codes(apps, schema_editor):
    LanguageScript = apps.get_model("corpus", "LanguageScript")
    # populate language codes for language scripts
    # used in current transcriptions
    codes = {
        "Judaeo-Arabic": "jrb",
        "Arabic": "ar",  # ara if we want to use ISO 639-2
        "Hebrew": "he",
        "Greek": "grc",
        "Aramaic": "arc",
        "Ladino": "lad",
        "Romance": "roa",
    }

    for script, code in codes.items():
        # try finding by display name first
        lang = LanguageScript.objects.filter(display_name=script).first()
        # if that fails, try searching on language & script together
        if not lang:
            lang = LanguageScript.objects.filter(language=script, script=script).first()
        # if we found a match, set the code and save
        if lang:
            lang.iso_code = code
            lang.save()


class Migration(migrations.Migration):

    dependencies = [
        ("corpus", "0021_languagescript_iso_code"),
    ]

    operations = [
        migrations.RunPython(populate_language_codes, migrations.RunPython.noop),
    ]
