# Generated by Django 3.2.8 on 2022-01-05 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("corpus", "0024_fragment_manifest"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentPrefetchableProxy",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("corpus.document",),
        ),
    ]
