# Generated by Django 3.2.8 on 2022-01-20 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("corpus", "0025_documentprefetchableproxy"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DocumentPrefetchableProxy",
        ),
    ]
