# Generated by Django 3.2.9 on 2022-01-06 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("corpus", "0025_documentprefetchableproxy"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentNeedsReview",
            fields=[],
            options={
                "verbose_name_plural": "Documents needing review",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("corpus.document",),
        ),
    ]
