# Generated by Django 3.2.8 on 2022-02-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpus", "0026_delete_documentprefetchableproxy"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="description_ar",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="description_he",
            field=models.TextField(blank=True, null=True),
        ),
    ]
