# Generated by Django 3.2.8 on 2022-02-25 15:36

from django.db import migrations, models
from django.db.models import F


def translate_existing_names(apps, schema_editor):
    # This would normally be accomplished by running update_translation_fields,
    # but tests rely on some existing records and need this to happen automatically.
    DocumentType = apps.get_model("corpus", "DocumentType")
    DocumentType.objects.all().update(
        name_en=F("name"), display_label_en=F("display_label")
    )


class Migration(migrations.Migration):

    dependencies = [
        ("corpus", "0027_translate_document_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="documenttype",
            name="display_label_ar",
            field=models.CharField(
                blank=True,
                help_text="Optional label for display on the public site",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="documenttype",
            name="display_label_en",
            field=models.CharField(
                blank=True,
                help_text="Optional label for display on the public site",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="documenttype",
            name="display_label_he",
            field=models.CharField(
                blank=True,
                help_text="Optional label for display on the public site",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="documenttype",
            name="name_ar",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="documenttype",
            name="name_en",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="documenttype",
            name="name_he",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.RunPython(translate_existing_names, migrations.RunPython.noop),
    ]
