# Generated by Django 3.2.11 on 2022-04-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpus", "0028_translate_documenttype"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="shelfmark_override",
            field=models.CharField(
                blank=True,
                help_text="Override default shelfmark display, e.g. to indicate a range of shelfmarks.",
                max_length=500,
                verbose_name="Shelfmark Override",
            ),
        ),
    ]
