# Generated by Django 3.2.11 on 2022-03-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpus", "0028_translate_documenttype"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="shelfmark_display_override",
            field=models.CharField(
                blank=True,
                help_text='Override default display of joins. This is especially useful for continuous shelfmark joins, e.g. "Bodl. MS Heb. d 66/49–50"',
                max_length=500,
                verbose_name="Shelfmark Display Override",
            ),
        ),
    ]
