# Generated by Django 3.2.13 on 2022-05-12 19:17

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpus", "0030_clean_iiif_urls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="doc_date_standard",
            field=models.CharField(
                blank=True,
                help_text="CE date (convert to Julian before 1582, Gregorian after 1582). Use YYYY, YYYY-MM, YYYY-MM-DD format or YYYY-MM-DD/YYYY-MM-DD for date ranges.",
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile(
                            "^\\d{3,4}(-[01]\\d(-[0-3]\\d)?)?(/\\d{3,4}(-[01]\\d(-[0-3]\\d)?)?)?$"
                        )
                    )
                ],
                verbose_name="Document date (standardized)",
            ),
        ),
    ]
