# Generated by Django 3.2.14 on 2022-07-19 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0003_taggeditem_add_unique_index"),
        ("corpus", "0032_revise_standard_date_help_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="TagMetadata",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_count", models.IntegerField(default=0)),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="taggit.tag"
                    ),
                ),
            ],
        ),
    ]
