# Generated by Django 3.2.13 on 2022-07-27 17:52

import django.contrib.postgres.fields
from django.db import migrations, models


def side_to_selected_images(apps, schema_editor):
    # remap "side" field to "selected images" (indices of recto, verso, both)
    TextBlock = apps.get_model("corpus", "TextBlock")
    tbs_with_side = TextBlock.objects.exclude(side="")
    for tb in tbs_with_side:
        selected_images = []
        if tb.side in ["r", "rv"]:
            selected_images.append(0)
        if tb.side in ["v", "rv"]:
            selected_images.append(1)
        tb.selected_images = selected_images
    TextBlock.objects.bulk_update(tbs_with_side, ["selected_images"])


def selected_images_to_side(apps, schema_editor):
    # reverse: "selected images" field to "side" (recto, verso, both)
    TextBlock = apps.get_model("corpus", "TextBlock")
    tbs_with_selected = TextBlock.objects.exclude(selected_images__len=0)
    for tb in tbs_with_selected:
        if len(tb.selected_images) == 1:
            if tb.selected_images[0] == 0:
                tb.side = "r"
            elif tb.selected_images[0] == 1:
                tb.side = "v"
        elif len(tb.selected_images) == 2 and all(
            i in tb.selected_images for i in [0, 1]
        ):
            tb.side = "rv"
    TextBlock.objects.bulk_update(tbs_with_selected, ["side"])


class Migration(migrations.Migration):

    dependencies = [
        ("corpus", "0032_revise_standard_date_help_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="textblock",
            name="selected_images",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="Selected image indices",
            ),
        ),
        migrations.RunPython(
            side_to_selected_images, reverse_code=selected_images_to_side
        ),
        migrations.RemoveField(
            model_name="textblock",
            name="side",
        ),
    ]
