# Generated by Django 3.2.14 on 2022-08-23 18:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpus", "0034_merge_duplicate_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="image_order_override",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.URLField(),
                null=True,
                size=None,
                verbose_name="Image Order",
            ),
        ),
    ]
