# Generated by Django 3.2.16 on 2023-01-26 17:53

from django.db import migrations
from django.db.models import Q


def populate_selected_images(apps, schema_editor):
    # populate selected_images with all image indices when it has length 0
    TextBlock = apps.get_model("corpus", "TextBlock")
    # exclude fragments without images
    tbs_without_selected = TextBlock.objects.filter(selected_images__len=0).exclude(
        Q(fragment__manifest__isnull=True), Q(fragment__iiif_url__exact="")
    )
    for tb in tbs_without_selected:
        # since we can't call iiif_images model method here, just use canvas count.
        # quick check of current data shows that all of them have cached manifests.
        image_count = tb.fragment.manifest.canvases.count()
        tb.selected_images = list(range(image_count))
    TextBlock.objects.bulk_update(tbs_without_selected, ["selected_images"])


class Migration(migrations.Migration):

    dependencies = [
        ("corpus", "0035_document_image_order_override"),
    ]

    operations = [
        migrations.RunPython(
            populate_selected_images, reverse_code=migrations.RunPython.noop
        )
    ]
