# Generated by Django 3.2.16 on 2023-01-26 21:34

from django.db import migrations


def merge_jts_ena(apps, schema_editor):
    """Merge JTS and ENA collections into just JTS and migrate all fragments
    to the merged collection"""
    Collection = apps.get_model("corpus", "Collection")
    Fragment = apps.get_model("corpus", "Fragment")
    try:
        ena = Collection.objects.get(abbrev="ENA")
        jts = Collection.objects.get(lib_abbrev="JTS", abbrev="")
    except Collection.DoesNotExist:
        # if ENA or JTS collection doesn't exist then we don't need this migration!
        return

    # reassign all fragments
    ena_fragments = ena.fragment_set.all()
    for frag in ena_fragments:
        frag.collection = jts
    Fragment.objects.bulk_update(ena_fragments, ["collection"])

    # delete the now empty ENA collection
    ena.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("corpus", "0035_document_image_order_override"),
    ]

    operations = [migrations.RunPython(merge_jts_ena, migrations.RunPython.noop)]
