# Generated by Django 3.2.16 on 2023-03-15 16:47

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpus", "0038_document_dating_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dating",
            name="standard_date",
            field=models.CharField(
                help_text="Convert to Julian before 1582, Gregorian after 1582. \nUse YYYY, YYYY-MM, YYYY-MM-DD format or YYYY-MM-DD/YYYY-MM-DD for date ranges.",
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile(
                            "^\\d{3,4}(-[01]\\d(-[0-3]\\d)?)?(/\\d{3,4}(-[01]\\d(-[0-3]\\d)?)?)?$"
                        )
                    )
                ],
                verbose_name="CE date",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="doc_date_original",
            field=models.CharField(
                blank=True,
                help_text="Explicit date on the document, in original format",
                max_length=255,
                verbose_name="Date on document",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="doc_date_standard",
            field=models.CharField(
                blank=True,
                help_text="Convert to Julian before 1582, Gregorian after 1582. \nUse YYYY, YYYY-MM, YYYY-MM-DD format or YYYY-MM-DD/YYYY-MM-DD for date ranges. \nLeave blank or clear out to automatically calculate standardized date for supported calendars.",
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile(
                            "^\\d{3,4}(-[01]\\d(-[0-3]\\d)?)?(/\\d{3,4}(-[01]\\d(-[0-3]\\d)?)?)?$"
                        )
                    )
                ],
                verbose_name="CE date",
            ),
        ),
    ]
