# Generated by Django 3.2.16 on 2023-05-22 14:39

from django.db import migrations

CONTENT_ADMIN = "Content Admin"
# missing Taggit permissions for content admin (already present for Content Editor)
taggit_perms = [
    "add_taggeditem",
    "change_taggeditem",
    "delete_taggeditem",
    "view_taggeditem",
]


def grant_tagmerge_permissions(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    admin_group = Group.objects.get(name=CONTENT_ADMIN)
    permissions = []
    for codename in taggit_perms:
        # using explicit get so that there will be an error if an
        # expected permission is not found)
        permissions.append(Permission.objects.get(codename=codename))
    # update both groups to add dating permissions
    admin_group.permissions.add(*permissions)


class Migration(migrations.Migration):

    dependencies = [
        ("corpus", "0039_document_ce_date"),
    ]
    operations = [
        migrations.RunPython(
            grant_tagmerge_permissions, reverse_code=migrations.RunPython.noop
        )
    ]
