# Generated by Django 3.2.16 on 2023-05-22 14:39

from django.contrib.auth.management import create_permissions
from django.db import migrations

CONTENT_ADMIN = "Content Admin"
# missing Taggit permissions for content admin (already present for Content Editor)
taggit_perms = [
    "add_taggeditem",
    "change_taggeditem",
    "delete_taggeditem",
    "view_taggeditem",
]


def grant_tagmerge_permissions(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    # make sure permissions are created before loading the fixture
    # which references them
    # (when running migrations all at once, permissions may not yet exist)
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=0)
        app_config.models_module = None

    admin_group = Group.objects.get(name=CONTENT_ADMIN)
    permissions = []
    for codename in taggit_perms:
        # using explicit get so that there will be an error if an
        # expected permission is not found)
        permissions.append(Permission.objects.get(codename=codename))
    # update both groups to add dating permissions
    admin_group.permissions.add(*permissions)


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0008_preload_github_coauthors"),
        ("corpus", "0039_document_ce_date"),
    ]
    operations = [
        migrations.RunPython(
            grant_tagmerge_permissions, reverse_code=migrations.RunPython.noop
        )
    ]
