# Generated by Django 3.2.16 on 2023-06-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpus", "0040_tag_merge_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="dating",
            name="rationale",
            field=models.CharField(
                choices=[
                    ("PA", "Paleography"),
                    ("PE", "Person mentioned"),
                    ("E", "Event mentioned"),
                    ("C", "Coinage"),
                    ("O", "Other (please specify)"),
                ],
                default="O",
                help_text="An explanation for how this date was inferred",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="dating",
            name="notes",
            field=models.TextField(
                help_text="Optional further details about the rationale"
            ),
        ),
    ]
