# Generated by Django 3.2.16 on 2023-07-13 16:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corpus", "0040_tag_merge_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="image_rotation_override",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                null=True,
                size=None,
                verbose_name="Image Rotation",
            ),
        ),
    ]
