# Generated by Django 3.2.16 on 2023-08-07 18:16

from django.db import migrations, models


def image_order_to_json(apps, schema_editor):
    # convert image_order_override array to the new JSONField format:
    # image_overrides = {canvas_uri: {'order': n}}
    Document = apps.get_model("corpus", "Document")
    docs = Document.objects.filter(image_order_override__isnull=False).exclude(
        image_order_override=[]
    )
    for document in docs:
        # set "order" value based on index in order override
        for idx, canvas_uri in enumerate(document.image_order_override):
            document.image_overrides[canvas_uri] = {"order": idx}
    Document.objects.bulk_update(docs, ["image_overrides"])


def image_overrides_to_order_array(apps, schema_editor):
    # reverse of the above
    Document = apps.get_model("corpus", "Document")
    docs = Document.objects.exclude(image_overrides={})

    for document in docs:
        # get canvas uris (i.e. jsonfield keys) in overridden order (i.e. sorted by "order" key)
        document.image_order_override = [
            canvas_uri
            for canvas_uri, _ in sorted(
                document.image_overrides.items(), key=lambda item: item[1]["order"]
            )
        ]
    Document.objects.bulk_update(docs, ["image_order_override"])


class Migration(migrations.Migration):
    dependencies = [
        ("corpus", "0041_dating_rationale"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="image_overrides",
            field=models.JSONField(
                null=False,
                blank=True,
                default=dict,
                verbose_name="Image Order/Rotation",
            ),
        ),
        migrations.RunPython(
            code=image_order_to_json, reverse_code=image_overrides_to_order_array
        ),
        migrations.RemoveField(
            model_name="document",
            name="image_order_override",
        ),
    ]
