# Generated by Django 3.2.23 on 2024-03-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0021_event"),
        ("corpus", "0045_fragment_provenance"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="events",
            field=models.ManyToManyField(
                related_name="documents",
                to="entities.Event",
                verbose_name="Related Events",
            ),
        ),
    ]
