# Generated by Django 3.2.23 on 2024-11-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corpus", "0046_document_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="Link to this collection on the web",
                verbose_name="URL",
            ),
        ),
    ]
