# Generated by Django 5.2.4 on 2025-07-16 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpus", "0048_fragment_provenance_display"),
        ("footnotes", "0037_creator_creator_unique_name_first_name_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="cite_description",
            field=models.BooleanField(
                default=False,
                help_text="If checked, the authors selected below will appear in the citation at the bottom of the public document page.",
                verbose_name="Cite description",
            ),
        ),
        migrations.CreateModel(
            name="DescriptionAuthorship",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=1)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="footnotes.creator",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="corpus.document",
                    ),
                ),
            ],
            options={
                "ordering": ("sort_order",),
            },
        ),
        migrations.AddField(
            model_name="document",
            name="authors",
            field=models.ManyToManyField(
                through="corpus.DescriptionAuthorship",
                to="footnotes.creator",
                verbose_name="Description Authors",
            ),
        ),
    ]
