# Generated by Django 5.2.4 on 2025-08-14 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("corpus", "0049_document_cite_description_descriptionauthorship_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="cite_description",
        ),
    ]
