# Generated by Django 5.2.4 on 2025-08-13 15:39

import django.db.models.deletion
from django.contrib.auth.management import create_permissions
from django.db import migrations, models

CONTENT_EDITOR = "Content Editor"
CONTENT_ADMIN = "Content Admin"
# new Provenance related permissions for content editor and admin
material_support_perms = [
    "change_materialsupport",
    "add_materialsupport",
    "view_materialsupport",
    "delete_materialsupport",
]


def grant_material_support_permissions(apps, schema_editor):
    group = apps.get_model("auth", "Group")
    permission = apps.get_model("auth", "Permission")

    # make sure permissions are created before loading the fixture
    # which references them
    # (when running migrations all at once, permissions may not yet exist)
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=0)
        app_config.models_module = None

    editor_group = group.objects.get(name=CONTENT_EDITOR)
    admin_group = group.objects.get(name=CONTENT_ADMIN)
    permissions = []
    for code_name in material_support_perms:
        # using explicit get so that there will be an error if an
        # expected permission is not found
        permissions.append(permission.objects.get(codename=code_name))
    # update both groups to add provenance permissions
    editor_group.permissions.add(*permissions)
    admin_group.permissions.add(*permissions)


def populate_material_support_display(apps, schema_editor):
    """Populate the initial Provenance options"""
    ms = apps.get_model("corpus", "MaterialSupport")
    ms_options = ["Paper", "Parchment", "Other", "Unknown"]
    for ms_option in ms_options:
        ms.objects.get_or_create(name=ms_option, name_en=ms_option)


class Migration(migrations.Migration):

    dependencies = [
        ("corpus", "0050_remove_document_cite_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialSupport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("name_en", models.CharField(max_length=255, null=True)),
                ("name_he", models.CharField(max_length=255, null=True)),
                ("name_ar", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="fragment",
            name="material_support",
            field=models.ForeignKey(
                blank=True,
                help_text="The physical material of the fragment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="corpus.materialsupport",
                verbose_name="Material support",
            ),
        ),
        migrations.RunPython(
            grant_material_support_permissions, migrations.RunPython.noop
        ),
        migrations.RunPython(
            populate_material_support_display, migrations.RunPython.noop
        ),
    ]
