# Generated by Django 5.2.4 on 2025-08-28 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("corpus", "0051_materialsupport_fragment_material_support"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="languagescript",
            options={
                "ordering": ["display_name", "language"],
                "verbose_name": "Language + Script",
                "verbose_name_plural": "Languages + Scripts",
            },
        ),
    ]
