# Generated by Django 5.2.4 on 2026-07-07 16:25

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpus", "0052_alter_documenttype_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="doc_date_standard",
            field=models.CharField(
                blank=True,
                help_text="Convert to Julian before 1582, Gregorian after 1582. \nUse YYYY, YYYY-MM, YYYY-MM-DD format or YYYY-MM-DD/YYYY-MM-DD for date ranges. \nLeave blank or clear out to automatically calculate standardized date for supported calendars.",
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile(
                            "^\\d{3,4}(-[01]\\d(-[0-3]\\d)?)?(/\\d{3,4}(-[01]\\d(-[0-3]\\d)?)?)?$"
                        ),
                        message="Enter a valid CE date as YYYY, YYYY-MM, YYYY-MM-DD, or a range (e.g. 1148/1149).",
                    )
                ],
                verbose_name="CE date",
            ),
        ),
    ]
