# Generated by Django 3.1.7 on 2021-03-30 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('corpus', '0008_update_shelfmark_helptext'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('E', 'Edition'), ('T', 'Translation'), ('D', 'Discussion')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('publish_date', models.DateTimeField(blank=True)),
                ('edition_number', models.CharField(blank=True, max_length=255)),
                ('volume', models.CharField(blank=True, max_length=255)),
                ('page_range', models.CharField(help_text='The range of pages being cited. Please do not include "p", "pg", etc. and follow the format # or #-#', max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.person')),
                ('published_language', models.ForeignKey(help_text='In what language was the source published?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='corpus.languagescript')),
                ('sourcetypes', models.ManyToManyField(to='footnotes.SourceType')),
            ],
        ),
    ]
