# Generated by Django 3.1.7 on 2021-04-01 14:56

from django.db import migrations


SOURCE_TYPES = ["Book", "Article", "Unpublished", "Dissertation", "Blog"]


def load_initial_sourcetypes(apps, schema_editor):
    # Load initial source types provided by the team
    SourceType = apps.get_model("footnotes", "SourceType")

    for sourcetype in SOURCE_TYPES:
        SourceType.objects.get_or_create(type=sourcetype)


SOURCE_LANGUAGES = [
    ("English", "en"),
    ("German", "de"),
    ("Hebrew", "he"),
]


def load_initial_languages(apps, schema_editor):
    # Load initial source languages
    SourceLanguage = apps.get_model("footnotes", "SourceLanguage")

    for lang, code in SOURCE_LANGUAGES:
        SourceLanguage.objects.get_or_create(name=lang, code=code)


class Migration(migrations.Migration):

    dependencies = [
        ("footnotes", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            load_initial_sourcetypes, reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            load_initial_languages, reverse_code=migrations.RunPython.noop
        ),
    ]
