# Generated by Django 3.1.7 on 2021-03-30 17:34

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('footnotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['author__last_name']},
        ),
        migrations.RenameField(
            model_name='source',
            old_name='published_language',
            new_name='language',
        ),
        migrations.RemoveField(
            model_name='source',
            name='sourcetypes',
        ),
        migrations.AddField(
            model_name='source',
            name='document_relations',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('E', 'Edition'), ('T', 'Translation'), ('D', 'Discussion')], default='E', help_text='How does the document relate to a source?', max_length=5),
        ),
        migrations.AddField(
            model_name='source',
            name='source_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='footnotes.sourcetype'),
        ),
        migrations.AlterField(
            model_name='source',
            name='page_range',
            field=models.CharField(blank=True, help_text='The range of pages being cited. Please do not include "p", "pg", etc. and follow the format # or #-#', max_length=255),
        ),
        migrations.AlterField(
            model_name='source',
            name='publish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sourcetype',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
