# Generated by Django 3.1.7 on 2021-04-01 14:56

from django.db import migrations

def load_existing_sourcetypes(apps, schema_editor):
    # Load all original sourcetypes listed
    SourceType = apps.get_model('footnotes', 'SourceType')

    SOURCE_TYPES = ['Book', 'Article', 'Unpublished', 'Dissertation', 'Blog']

    for sourcetype in SOURCE_TYPES:
        SourceType.objects.get_or_create(type=sourcetype)


class Migration(migrations.Migration):

    dependencies = [
        ('footnotes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_existing_sourcetypes,
                             reverse_code=migrations.RunPython.noop),
    ]
