# Generated by Django 3.1.6 on 2021-03-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footnotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='title_he',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
