# Generated by Django 3.1.7 on 2021-04-01 14:34

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('footnotes', '0002_multilingual_source_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['author__sort_name']},
        ),
        migrations.AlterField(
            model_name='footnote',
            name='document_relation_types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('E', 'Edition'), ('T', 'Translation'), ('D', 'Discussion')], help_text='How does the document relate to a source?', max_length=5),
        ),
    ]
