# Generated by Django 3.1.7 on 2021-04-26 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footnotes', '0003_add_footnotes_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['title', 'year']},
        ),
        migrations.RenameField(
            model_name='source',
            old_name='author',
            new_name='authors',
        ),
    ]
