# Generated by Django 3.1 on 2021-05-13 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("footnotes", "0005_footnote_object_id_gfklookupfield"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="footnote",
            options={"ordering": ["source", "location"]},
        ),
    ]
