# Generated by Django 3.1.7 on 2021-04-01 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('footnotes', '0006_rename_edition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('first_name_en', models.CharField(max_length=255, null=True)),
                ('first_name_he', models.CharField(max_length=255, null=True)),
                ('first_name_ar', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('last_name_en', models.CharField(max_length=255, null=True)),
                ('last_name_he', models.CharField(max_length=255, null=True)),
                ('last_name_ar', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='source',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footnotes.creator'),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['author']},
        ),
    ]
