# Generated by Django 3.1 on 2021-05-19 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("footnotes", "0007_increase_source_url_maxlength"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footnote",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(app_label="corpus"),
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
