# Generated by Django 3.1 on 2021-05-21 00:10

from django.db import migrations


def create_booksection_sourcetype(apps, schema_editor):
    # Load initial source types provided by the team
    SourceType = apps.get_model("footnotes", "SourceType")
    SourceType.objects.get_or_create(type="Book Section")


class Migration(migrations.Migration):

    dependencies = [
        ("footnotes", "0009_add_source_journal_and_footnote_url"),
    ]

    operations = [
        migrations.RunPython(
            create_booksection_sourcetype, reverse_code=migrations.RunPython.noop
        ),
    ]
