# Generated by Django 3.2.8 on 2021-11-23 15:54

import re

from django.db import migrations


def populate_page_ranges(apps, schema_editor):
    Source = apps.get_model("footnotes", "Source")
    sources = Source.objects.exclude(other_info__isnull=True).exclude(
        other_info__exact=""
    )
    for source in sources:
        reg = re.search(r"(\d+)(–|-)(\d+)", source.other_info)
        if reg:
            source.page_range = "%s–%s" % (reg.group(1), reg.group(3))
            source.save()


class Migration(migrations.Migration):

    dependencies = [
        ("footnotes", "0013_add_place_and_publisher_to_source"),
    ]

    operations = [
        migrations.RunPython(populate_page_ranges),
    ]
