# Generated by Django 3.2.11 on 2022-04-28 20:34

from django.db import migrations


def populate_location_sort(apps, schema_editor):
    Footnote = apps.get_model("footnotes", "Footnote")
    # save all footnotes with a location set so that the
    # location sort pre_save method will run and populate the sort field
    for fn in Footnote.objects.exclude(location=""):
        fn.save()


class Migration(migrations.Migration):

    dependencies = [
        ("footnotes", "0017_footnote_location_sort"),
    ]

    operations = [
        migrations.RunPython(
            populate_location_sort, reverse_code=migrations.RunPython.noop
        ),
    ]
