# Generated by Django 3.2.13 on 2022-05-03 18:45

import gfklookupwidget.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("footnotes", "0018_populate_footnote_location_sort"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footnote",
            name="object_id",
            field=gfklookupwidget.fields.GfkLookupField(
                help_text="If content type is Document, this is PGPID"
            ),
        ),
    ]
