# Generated by Django 3.2.13 on 2022-07-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("footnotes", "0019_alter_footnote_object_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footnote",
            name="content",
            field=models.JSONField(
                blank=True,
                help_text="Transcription content (transitional; edit with care and only when needed)",
                null=True,
            ),
        ),
    ]
