# Generated by Django 3.2.14 on 2022-08-23 15:19

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("footnotes", "0020_alter_footnote_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footnote",
            name="doc_relation",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("E", "Edition"),
                    ("T", "Translation"),
                    ("D", "Discussion"),
                    ("X", "Digital Edition"),
                ],
                help_text="How does the source relate to this document?",
                max_length=7,
                verbose_name="Document relation",
            ),
        ),
    ]
