# Generated by Django 3.2.13 on 2022-08-26 17:05

import django.db.models.expressions
import django.db.models.functions.comparison
import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("footnotes", "0020_alter_footnote_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="footnote",
            options={
                "ordering": [
                    "source",
                    django.db.models.expressions.OrderBy(
                        django.db.models.functions.comparison.NullIf(
                            "location_sort", django.db.models.expressions.Value("")
                        ),
                        nulls_last=True,
                    ),
                ]
            },
        ),
        migrations.AlterField(
            model_name="footnote",
            name="doc_relation",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("E", "Edition"),
                    ("T", "Translation"),
                    ("D", "Discussion"),
                    ("X", "Digital Edition"),
                ],
                help_text="How does the source relate to this document?",
                max_length=7,
                verbose_name="Document relation",
            ),
        ),
    ]
