# Generated by Django 3.2.14 on 2022-11-17 21:34

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("footnotes", "0022_footnote_one_digital_edition_per_document_and_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footnote",
            name="doc_relation",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("E", "Edition"),
                    ("T", "Translation"),
                    ("D", "Discussion"),
                    ("X", "Digital Edition"),
                ],
                help_text="How does the source relate to this document?",
                max_length=7,
                null=True,
                verbose_name="Document relation",
            ),
        ),
    ]
