# Generated by Django 3.2.13 on 2022-10-10 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("footnotes", "0022_footnote_one_digital_edition_per_document_and_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="footnote",
            name="content",
        ),
    ]
