# Generated by Django 3.2.14 on 2022-12-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("footnotes", "0023_alter_footnote_doc_relation"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="footnote",
            name="one_digital_edition_per_document_and_source",
        ),
        migrations.AddConstraint(
            model_name="footnote",
            constraint=models.UniqueConstraint(
                condition=models.Q(("doc_relation__contains", "X")),
                fields=("source", "object_id", "content_type"),
                name="one_digital_edition_per_document_and_source",
            ),
        ),
    ]
