# Generated by Django 3.2.16 on 2023-02-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("footnotes", "0025_alter_footnote_doc_relation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footnote",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text='Displays publicly. For minor emendations to a transcription, put "with minor emendations by [your name, date]." Do not add a note for typo corrections. For significant alterations to a transcription, create a new source indicating co-authorship.',
            ),
        ),
    ]
