# Generated by Django 3.2.16 on 2023-03-23 17:43

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("footnotes", "0026_alter_footnote_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footnote",
            name="doc_relation",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("E", "Edition"),
                    ("T", "Translation"),
                    ("D", "Discussion"),
                    ("X", "Digital Edition"),
                    ("Y", "Digital Translation"),
                ],
                help_text='How does the source relate to this document? Please note: "Edition" is a (published or unpublished) transcription. "Digital edition" is the PGP version of an edition, and the source record should NOT be deleted. Footnotes for "editions" and "digital editions" should NOT be combined, even if they refer to the same transcription.',
                max_length=9,
                null=True,
                verbose_name="Document relation",
            ),
        ),
    ]
