# Generated by Django 3.2.16 on 2023-07-18 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("footnotes", "0028_sourcelanguage_direction"),
        ("corpus", "0037_create_dating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="languages",
            field=models.ManyToManyField(
                help_text="The language(s) the source is written in. Note: Sources should never include\n        transcription language unless the entire source consists of a transcription.",
                to="footnotes.SourceLanguage",
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="source_type",
            field=models.ForeignKey(
                help_text="The form of the source's publication. Note: for unpublished sources, be sure\n        to create separate Source records for unpublished transcriptions and unpublished\n        translations, even if they reside on the same digital document.",
                on_delete=django.db.models.deletion.CASCADE,
                to="footnotes.sourcetype",
            ),
        ),
    ]
