# Generated by Django 3.2.16 on 2023-08-22 19:13

from django.db import migrations, models


def create_unspecified_source_language(apps, schema_editor):
    SourceLanguage = apps.get_model("footnotes", "SourceLanguage")
    SourceLanguage.objects.get_or_create(
        name="Unspecified (unpublished transcriptions)", code="zxx"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("footnotes", "0030_digital_footnote_location"),
    ]

    operations = [
        migrations.RunPython(
            create_unspecified_source_language,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="source",
            name="languages",
            field=models.ManyToManyField(
                help_text="The language(s) the source is written in. Note: The Unspecified language\n        option should only ever be used for unpublished transcriptions, as the language of the\n        transcription is already marked on the document.",
                to="footnotes.SourceLanguage",
            ),
        ),
    ]
