# Generated by Django 3.2.23 on 2025-02-04 19:35

import re

from django.db import migrations


def populate_emendations(apps, schema_editor):
    """Catch a bunch of the most common kinds of emendations notes with one or
    two contributors, and auto-populate the emendations field with them."""
    Footnote = apps.get_model("footnotes", "Footnote")
    emendations_regex = r"s by ([\w ]+[\w]) \((\d+)\)"
    emendations_multi_regex = r"(\)|\)\,) and ([\w ]+[\w]) \((\d+)\)"
    for fn in Footnote.objects.filter(notes__regex=emendations_regex):
        match = re.search(emendations_regex, fn.notes)
        name = match.group(1)
        year = match.group(2)
        emendations = f"{name}, {year}"
        match2 = re.search(emendations_multi_regex, fn.notes)
        if match2:
            name2 = match2.group(2)
            year2 = match2.group(3)
            emendations = f"{emendations} and {name2}, {year2}"
        fn.emendations = emendations
        fn.save()


class Migration(migrations.Migration):
    dependencies = [
        ("footnotes", "0033_footnote_emendations"),
    ]

    operations = [
        migrations.RunPython(
            populate_emendations,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
