# Generated by Django 3.2.23 on 2025-02-18 20:25

from django.db import migrations, models

NON_LATIN_SOURCE_LANGUAGES = [
    ("Hebrew", "he"),
    ("Arabic", "ar"),
    ("Judaeo-Arabic", "jrb"),
]


def set_non_latin(apps, schema_editor):
    SourceLanguage = apps.get_model("footnotes", "SourceLanguage")
    for lang, code in NON_LATIN_SOURCE_LANGUAGES:
        sl, _ = SourceLanguage.objects.get_or_create(name=lang, code=code)
        sl.non_latin = True
        sl.save()


class Migration(migrations.Migration):
    dependencies = [
        ("footnotes", "0034_populate_footnote_emendations"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcelanguage",
            name="non_latin",
            field=models.BooleanField(
                default=False,
                help_text="True if this language uses a non-Latin script, and therefore should be included in formatted citations for associated Source records.",
                verbose_name="Uses non-Latin script",
            ),
        ),
        migrations.RunPython(set_non_latin, migrations.RunPython.noop),
    ]
