# Generated by Django 5.2.4 on 2025-07-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("footnotes", "0036_alter_footnote_emendations"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="creator",
            constraint=models.UniqueConstraint(
                fields=("first_name_en", "last_name"),
                name="creator_unique_name-first_name_en",
            ),
        ),
        migrations.AddConstraint(
            model_name="creator",
            constraint=models.UniqueConstraint(
                fields=("first_name_he", "last_name"),
                name="creator_unique_name-first_name_he",
            ),
        ),
        migrations.AddConstraint(
            model_name="creator",
            constraint=models.UniqueConstraint(
                fields=("first_name_ar", "last_name"),
                name="creator_unique_name-first_name_ar",
            ),
        ),
        migrations.AddConstraint(
            model_name="creator",
            constraint=models.UniqueConstraint(
                fields=("first_name", "last_name_en"),
                name="creator_unique_name-last_name_en",
            ),
        ),
        migrations.AddConstraint(
            model_name="creator",
            constraint=models.UniqueConstraint(
                fields=("first_name", "last_name_he"),
                name="creator_unique_name-last_name_he",
            ),
        ),
        migrations.AddConstraint(
            model_name="creator",
            constraint=models.UniqueConstraint(
                fields=("first_name", "last_name_ar"),
                name="creator_unique_name-last_name_ar",
            ),
        ),
    ]
