# Generated by Django 3.2.8 on 2021-12-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.AddConstraint(
            model_name="contributor",
            constraint=models.UniqueConstraint(
                fields=("first_name", "last_name"), name="contributor_unique_name"
            ),
        ),
    ]
