# Generated by Django 3.2.8 on 2021-12-27 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailredirects", "0006_redirect_increase_max_length"),
        ("wagtailforms", "0004_add_verbose_name_plural"),
        ("wagtailcore", "0066_collection_management_permissions"),
        ("pages", "0003_alter_contributors_translateable"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contributor",
        ),
        migrations.DeleteModel(
            name="CreditsPage",
        ),
    ]
