# Generated by Django 3.2.14 on 2022-12-05 16:17

from django.db import migrations


def delete_creditspage_instances(apps, schema_editor):
    """Delete any pages using the previously-deleted model CreditsPage (see migration 0004)"""
    Page = apps.get_model("wagtailcore", "Page")
    Page.objects.filter(content_type__model="creditspage").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_create_svgimageblock"),
    ]

    operations = [
        migrations.RunPython(delete_creditspage_instances, migrations.RunPython.noop)
    ]
