# Generated by Django 3.2.23 on 2024-10-18 20:43

import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0008_delete_creditspage_instances"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "paragraph",
                        wagtail.blocks.RichTextBlock(
                            features=[
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "underline",
                                "link",
                                "ol",
                                "ul",
                                "blockquote",
                                "superscript",
                                "subscript",
                                "strikethrough",
                            ],
                            required=False,
                        ),
                    ),
                    (
                        "collapsible_paragraph",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "label",
                                    wagtail.blocks.CharBlock(
                                        label="Heading label/question", required=True
                                    ),
                                ),
                                (
                                    "content",
                                    wagtail.blocks.RichTextBlock(
                                        features=[
                                            "bold",
                                            "italic",
                                            "underline",
                                            "link",
                                            "ol",
                                            "ul",
                                            "blockquote",
                                            "superscript",
                                            "subscript",
                                            "strikethrough",
                                        ],
                                        label="Expanded details/answer",
                                        required=True,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "image",
                        wagtail.blocks.StructBlock(
                            [
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    "alternative_text",
                                    wagtail.blocks.TextBlock(
                                        help_text="Alternative text for visually impaired users to\nbriefly communicate the intended message of the image in this context.",
                                        required=True,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.blocks.RichTextBlock(
                                        features=["link", "superscript"], required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "svg_image",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.documents.blocks.DocumentChooserBlock(),
                                ),
                                (
                                    "alternative_text",
                                    wagtail.blocks.TextBlock(
                                        help_text="Alternative text for visually impaired users to\nbriefly communicate the intended message of the image in this context.",
                                        required=True,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.blocks.RichTextBlock(
                                        features=["link", "superscript"], required=False
                                    ),
                                ),
                                (
                                    "extended_description",
                                    wagtail.blocks.RichTextBlock(
                                        features=["p"],
                                        help_text="This text will only be read to     non-sighted users and should describe the major insights or     takeaways from the graphic. Multiple paragraphs are allowed.",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "paragraph",
                        wagtail.blocks.RichTextBlock(
                            features=[
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "underline",
                                "link",
                                "ol",
                                "ul",
                                "blockquote",
                                "superscript",
                                "subscript",
                                "strikethrough",
                            ],
                            required=False,
                        ),
                    ),
                    (
                        "collapsible_paragraph",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "label",
                                    wagtail.blocks.CharBlock(
                                        label="Heading label/question", required=True
                                    ),
                                ),
                                (
                                    "content",
                                    wagtail.blocks.RichTextBlock(
                                        features=[
                                            "bold",
                                            "italic",
                                            "underline",
                                            "link",
                                            "ol",
                                            "ul",
                                            "blockquote",
                                            "superscript",
                                            "subscript",
                                            "strikethrough",
                                        ],
                                        label="Expanded details/answer",
                                        required=True,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "image",
                        wagtail.blocks.StructBlock(
                            [
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    "alternative_text",
                                    wagtail.blocks.TextBlock(
                                        help_text="Alternative text for visually impaired users to\nbriefly communicate the intended message of the image in this context.",
                                        required=True,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.blocks.RichTextBlock(
                                        features=["link", "superscript"], required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "svg_image",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.documents.blocks.DocumentChooserBlock(),
                                ),
                                (
                                    "alternative_text",
                                    wagtail.blocks.TextBlock(
                                        help_text="Alternative text for visually impaired users to\nbriefly communicate the intended message of the image in this context.",
                                        required=True,
                                    ),
                                ),
                                (
                                    "caption",
                                    wagtail.blocks.RichTextBlock(
                                        features=["link", "superscript"], required=False
                                    ),
                                ),
                                (
                                    "extended_description",
                                    wagtail.blocks.RichTextBlock(
                                        features=["p"],
                                        help_text="This text will only be read to     non-sighted users and should describe the major insights or     takeaways from the graphic. Multiple paragraphs are allowed.",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                ]
            ),
        ),
    ]
