# Generated by Django 5.2.4 on 2025-09-08 21:10

from django.contrib.auth.management import create_permissions
from django.db import migrations, models

CONTENT_EDITOR = "Content Editor"
CONTENT_ADMIN = "Content Admin"
# new Manuals related permissions for content editor and admin
manual_perms = [
    "change_manual",
    "add_manual",
    "view_manual",
    "delete_manual",
]


def grant_manual_permissions(apps, schema_editor):
    group = apps.get_model("auth", "Group")
    permission = apps.get_model("auth", "Permission")

    # make sure permissions are created before loading the fixture
    # which references them
    # (when running migrations all at once, permissions may not yet exist)
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=0)
        app_config.models_module = None

    editor_group = group.objects.get(name=CONTENT_EDITOR)
    admin_group = group.objects.get(name=CONTENT_ADMIN)
    permissions = []
    for code_name in manual_perms:
        # using explicit get so that there will be an error if an
        # expected permission is not found
        permissions.append(permission.objects.get(codename=code_name))
    # update both groups to add manual permissions
    editor_group.permissions.add(*permissions)
    admin_group.permissions.add(*permissions)


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Manual",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField(verbose_name="URL")),
            ],
        ),
        migrations.RunPython(grant_manual_permissions, migrations.RunPython.noop),
    ]
