# Generated by Django 3.2.14 on 2022-11-16 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("footnotes", "0022_footnote_one_digital_edition_per_document_and_source"),
        ("annotations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="footnote",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="footnotes.footnote",
            ),
        ),
    ]
