# Generated by Django 3.2.16 on 2023-10-20 18:51

from django.db import migrations


def cleanup_annotations(apps, schema_editor):
    """Cleanup all annotations with unicode nbsp in their labels or values"""
    Annotation = apps.get_model("annotations", "Annotation")
    for anno in Annotation.objects.filter(content__icontains="\xa0"):
        for body in anno.content["body"]:
            if "label" in body:
                body["label"] = body["label"].replace("\xa0", " ")
            if "value" in body:
                body["value"] = body["value"].replace("\xa0", " ")
        anno.save()


class Migration(migrations.Migration):
    dependencies = [
        ("annotations", "0004_alter_annotation_footnote"),
    ]

    operations = [
        migrations.RunPython(
            cleanup_annotations, reverse_code=migrations.RunPython.noop
        )
    ]
