# Generated by Django 3.2.16 on 2024-02-07 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("annotations", "0005_annotation_cleanup_nbsp"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="block",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="annotations.annotation",
            ),
        ),
    ]
