# Generated by Django 3.2.16 on 2023-07-05 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corpus", "0040_tag_merge_permissions"),
        ("entities", "0002_populate_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="name",
            name="language",
            field=models.ForeignKey(
                help_text="Please indicate the language of most components of the name as written here.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="corpus.languagescript",
            ),
        ),
        migrations.AlterField(
            model_name="name",
            name="primary",
            field=models.BooleanField(
                default=False,
                help_text="Check box if this is the primary name that should be displayed on the site.",
                verbose_name="Display name",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="A description that will appear on the public Person page if 'Person page' box is checked.",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="description_ar",
            field=models.TextField(
                blank=True,
                help_text="A description that will appear on the public Person page if 'Person page' box is checked.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="description_en",
            field=models.TextField(
                blank=True,
                help_text="A description that will appear on the public Person page if 'Person page' box is checked.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="description_he",
            field=models.TextField(
                blank=True,
                help_text="A description that will appear on the public Person page if 'Person page' box is checked.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="has_page",
            field=models.BooleanField(
                default=False,
                help_text="Check box if this person should have a dedicated, public Person page on the PGP. If checked, please draft a public description below.",
                verbose_name="Person page",
            ),
        ),
    ]
