# Generated by Django 3.2.16 on 2023-07-11 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("footnotes", "0028_sourcelanguage_direction"),
        ("corpus", "0040_tag_merge_permissions"),
        ("entities", "0002_populate_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentPlaceRelationType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("name_en", models.CharField(max_length=255, null=True, unique=True)),
                ("name_he", models.CharField(max_length=255, null=True, unique=True)),
                ("name_ar", models.CharField(max_length=255, null=True, unique=True)),
            ],
            options={
                "verbose_name": "Document-Place relationship",
                "verbose_name_plural": "Document-Place relationships",
            },
        ),
        migrations.CreateModel(
            name="PersonPlaceRelationType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("name_en", models.CharField(max_length=255, null=True, unique=True)),
                ("name_he", models.CharField(max_length=255, null=True, unique=True)),
                ("name_ar", models.CharField(max_length=255, null=True, unique=True)),
            ],
            options={
                "verbose_name": "Person-Place relationship",
                "verbose_name_plural": "Person-Place relationships",
            },
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=6, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "footnotes",
                    models.ManyToManyField(
                        blank=True, related_name="places", to="footnotes.Footnote"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PersonPlaceRelation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="entities.person",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="entities.place"
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="entities.personplacerelationtype",
                        verbose_name="Relation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentPlaceRelation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="corpus.document",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="entities.place"
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="entities.documentplacerelationtype",
                        verbose_name="Relation",
                    ),
                ),
            ],
        ),
    ]
