# Generated by Django 3.2.16 on 2023-08-16 17:33

from django.contrib.auth.management import create_permissions
from django.db import migrations

CONTENT_EDITOR = "Content Editor"
# new permissions for content editor
content_editor_perms = [
    "add_name",
    "change_name",
    "delete_name",
    "view_name",
    "add_person",
    "change_person",
    "delete_person",
    "view_person",
    "add_persondocumentrelation",
    "change_persondocumentrelation",
    "delete_persondocumentrelation",
    "view_persondocumentrelation",
    "view_persondocumentrelationtype",
    "add_personpersonrelation",
    "change_personpersonrelation",
    "delete_personpersonrelation",
    "view_personpersonrelation",
    "view_personpersonrelationtype",
    "view_personrole",
]


CONTENT_ADMIN = "Content Admin"
# additional new permissions for content admin: add, change, delete relation types and person roles
content_admin_perms = [
    "add_personpersonrelationtype",
    "change_personpersonrelationtype",
    "delete_personpersonrelationtype",
    "add_persondocumentrelationtype",
    "change_persondocumentrelationtype",
    "delete_persondocumentrelationtype",
    "add_personrole",
    "change_personrole",
    "delete_personrole",
]


def set_entities_permissions(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    # make sure permissions are created before loading the fixture
    # which references them
    # (when running migrations all at once, permissions may not yet exist)
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=0)
        app_config.models_module = None

    editor_group = Group.objects.get(name=CONTENT_EDITOR)
    permissions = []
    for codename in content_editor_perms:
        # using explicit get so that there will be an error if an
        # expected permission is not found
        permissions.append(Permission.objects.get(codename=codename))
    editor_group.permissions.add(*permissions)

    # update content admin group; add to content edit permissions
    admin_group = Group.objects.get(name=CONTENT_ADMIN)
    for codename in content_admin_perms:
        permissions.append(Permission.objects.get(codename=codename))
    admin_group.permissions.add(*permissions)


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0003_help_text_and_verbose_names"),
        # relies on common for Groups to be created
        ("common", "0008_preload_github_coauthors"),
    ]

    operations = [
        migrations.RunPython(
            set_entities_permissions, reverse_code=migrations.RunPython.noop
        )
    ]
