# Generated by Django 3.2.16 on 2023-07-11 20:48

from django.db import migrations


def populate_place_types(apps, schema_editor):
    """Populate the English names for predetermined types of relationships."""
    PersonPlaceRelationType = apps.get_model("entities", "PersonPlaceRelationType")
    DocumentPlaceRelationType = apps.get_model("entities", "DocumentPlaceRelationType")

    person_place_relations = [
        "Home base",
        "Occasional trips to",
        "Family traces roots to",
    ]
    for relation in person_place_relations:
        PersonPlaceRelationType.objects.create(name=relation, name_en=relation)

    document_place_relations = [
        "Letter origin",
        "Letter destination",
    ]
    for relation in document_place_relations:
        DocumentPlaceRelationType.objects.create(name=relation, name_en=relation)


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0004_places"),
    ]

    operations = [
        migrations.RunPython(
            populate_place_types, reverse_code=migrations.RunPython.noop
        ),
    ]
