# Generated by Django 3.2.16 on 2023-08-09 17:52

from django.db import migrations

# remove the "one primary name per entity" constraint as this could cause
# unique constraint violations mid-transaction (e.g. an entity has two names
# and the primary name is switched from one name to the other)

# enforced at the admin form level instead


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0006_populate_place_types"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="name",
            name="one_primary_name_per_entity",
        ),
    ]
