# Generated by Django 3.2.16 on 2023-09-12 18:30

from django.db import migrations, models


def populate_ambiguous_types(apps, schema_editor):
    PersonPersonRelationType = apps.get_model("entities", "PersonPersonRelationType")
    new_types = ["Possibly the same person", "Not to be confused with"]
    for type_name in new_types:
        PersonPersonRelationType.objects.get_or_create(
            name=type_name, name_en=type_name, category="A"  # A = ambiguity
        )


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0009_personpersonrelationtype_converse_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personpersonrelationtype",
            name="category",
            field=models.CharField(
                choices=[
                    ("I", "Immediate family relations"),
                    ("E", "Extended family"),
                    ("M", "Relatives by marriage"),
                    ("B", "Business and property relationships"),
                    ("A", "Ambiguity"),
                ],
                max_length=1,
            ),
        ),
        migrations.RunPython(
            code=populate_ambiguous_types, reverse_code=migrations.RunPython.noop
        ),
    ]
