# Generated by Django 3.2.16 on 2023-10-12 20:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0010_alter_personpersonrelationtype_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="footnotes",
        ),
    ]
