# Generated by Django 3.2.16 on 2023-10-12 20:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0011_remove_person_footnotes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="place",
            name="footnotes",
        ),
    ]
