# Generated by Django 3.2.23 on 2024-02-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0012_remove_place_footnotes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Latitude as a numeric value between -90 and 90, with up to 4 decimal places\n        of precision. <br /><a href='https://www.fcc.gov/media/radio/dms-decimal'>This tool</a> can be\n        used to convert from degrees, minutes, seconds (DMS) to decimal.",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Longitude as a numeric value between -180 and 180, with up to 4 decimal places\n        of precision. <br /><a href='https://www.fcc.gov/media/radio/dms-decimal'>This tool</a> can be\n        used to convert from degrees, minutes, seconds (DMS) to decimal.",
                max_digits=7,
                null=True,
            ),
        ),
    ]
