# Generated by Django 3.2.23 on 2024-02-27 22:09

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0013_alter_place_latitude_longitude"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlacePlaceRelationType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("name_en", models.CharField(max_length=255, null=True, unique=True)),
                ("name_he", models.CharField(max_length=255, null=True, unique=True)),
                ("name_ar", models.CharField(max_length=255, null=True, unique=True)),
            ],
            options={
                "verbose_name": "Place-Place relationship",
                "verbose_name_plural": "Place-Place relationships",
            },
        ),
        migrations.CreateModel(
            name="PlacePlaceRelation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "place_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="place_b",
                        to="entities.place",
                    ),
                ),
                (
                    "place_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="place_a",
                        to="entities.place",
                        verbose_name="Place",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="entities.placeplacerelationtype",
                        verbose_name="Relation",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="placeplacerelation",
            constraint=models.UniqueConstraint(
                fields=("type", "place_a", "place_b"),
                name="unique_place_place_relation_by_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="placeplacerelation",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("place_a", django.db.models.expressions.F("place_b")),
                    _negated=True,
                ),
                name="entities_placeplacerelation_prevent_self_relationship",
            ),
        ),
    ]
