# Generated by Django 3.2.23 on 2024-02-28 19:01

from django.db import migrations


def populate_types(apps, schema_editor):
    """Populate the English names for predetermined types of relationships between places."""
    PlacePlaceRelationType = apps.get_model("entities", "PlacePlaceRelationType")
    for relation in ["Possibly the same as", "Not to be confused with"]:
        PlacePlaceRelationType.objects.create(name=relation, name_en=relation)


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0014_placeplacerelation"),
    ]

    operations = [
        migrations.RunPython(populate_types, reverse_code=migrations.RunPython.noop),
    ]
