# Generated by Django 3.2.23 on 2024-02-28 20:57

from django.contrib.auth.management import create_permissions
from django.db import migrations

CONTENT_EDITOR = "Content Editor"
# new permissions for content editor
content_editor_perms = [
    "add_placeplacerelation",
    "change_placeplacerelation",
    "delete_placeplacerelation",
    "view_placeplacerelation",
    "view_placeplacerelationtype",
]

CONTENT_ADMIN = "Content Admin"
# additional new permissions for content admin: add, change, delete relation types
content_admin_perms = [
    "add_placeplacerelationtype",
    "change_placeplacerelationtype",
    "delete_placeplacerelationtype",
]


def set_placeplacerelation_permissions(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    # make sure permissions are created before loading the fixture
    # which references them
    # (when running migrations all at once, permissions may not yet exist)
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=0)
        app_config.models_module = None

    editor_group = Group.objects.get(name=CONTENT_EDITOR)
    permissions = []
    for codename in content_editor_perms:
        # using explicit get so that there will be an error if an
        # expected permission is not found
        permissions.append(Permission.objects.get(codename=codename))
    editor_group.permissions.add(*permissions)

    # update content admin group; add to content edit permissions
    admin_group = Group.objects.get(name=CONTENT_ADMIN)
    for codename in content_admin_perms:
        permissions.append(Permission.objects.get(codename=codename))
    admin_group.permissions.add(*permissions)


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0015_populate_placeplacerelation_types"),
    ]

    operations = [
        migrations.RunPython(
            set_placeplacerelation_permissions, reverse_code=migrations.RunPython.noop
        )
    ]
