# Generated by Django 3.2.23 on 2024-02-29 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0016_placeplacerelation_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="placeplacerelation",
            name="place_a",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="place_b",
                to="entities.place",
                verbose_name="Place",
            ),
        ),
    ]
