# Generated by Django 3.2.23 on 2024-03-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0017_alter_placeplacerelation_place_a"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
