# Generated by Django 3.2.23 on 2024-03-06 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corpus", "0045_fragment_provenance"),
        ("entities", "0018_place_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="name",
            name="language",
            field=models.ForeignKey(
                help_text='Please indicate the language of most components of the name as written here. Refers to the language in which a name is written, not the linguistic origin of the name. Ex: "Nahray b. Nissim" should be marked as English.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="corpus.languagescript",
            ),
        ),
        migrations.AlterField(
            model_name="name",
            name="name",
            field=models.CharField(
                help_text="Please add common forms of the name in both English and other languages in which it appears in documents.",
                max_length=255,
            ),
        ),
    ]
