# Generated by Django 3.2.23 on 2024-03-11 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corpus", "0045_fragment_provenance"),
        ("entities", "0019_name_help_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="name",
            name="language",
            field=models.ForeignKey(
                help_text='Please indicate the language of most components of the name as written here. Refers to the language in which a name is written, not the linguistic origin of the name. Ex: “Nahray b. Nissim” and "Fusṭāṭ" should be marked as English.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="corpus.languagescript",
            ),
        ),
    ]
