# Generated by Django 3.2.23 on 2024-03-12 17:52

from django.contrib.auth.management import create_permissions
from django.db import migrations

CONTENT_EDITOR = "Content Editor"
CONTENT_ADMIN = "Content Admin"
# new permissions for events
event_perms = [
    "add_event",
    "change_event",
    "delete_event",
    "view_event",
    "add_documenteventrelation",
    "change_documenteventrelation",
    "delete_documenteventrelation",
    "view_documenteventrelation",
    "add_personeventrelation",
    "change_personeventrelation",
    "delete_personeventrelation",
    "view_personeventrelation",
    "add_placeeventrelation",
    "change_placeeventrelation",
    "delete_placeeventrelation",
    "view_placeeventrelation",
]


def set_event_permissions(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    # make sure permissions are created before loading the fixture
    # which references them
    # (when running migrations all at once, permissions may not yet exist)
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=0)
        app_config.models_module = None

    editor_group = Group.objects.get(name=CONTENT_EDITOR)
    permissions = []
    for codename in event_perms:
        # using explicit get so that there will be an error if an
        # expected permission is not found
        permissions.append(Permission.objects.get(codename=codename))
    editor_group.permissions.add(*permissions)
    admin_group = Group.objects.get(name=CONTENT_ADMIN)
    admin_group.permissions.add(*permissions)


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0021_event"),
    ]

    operations = [
        migrations.RunPython(
            set_event_permissions, reverse_code=migrations.RunPython.noop
        )
    ]
