# Generated by Django 3.2.23 on 2024-04-01 18:55

import django.db.models.deletion
from django.db import migrations, models
from slugify import slugify
from unidecode import unidecode


def populate_slugs(apps, schema_editor):
    """Popualte slugs for existing people.
    Code is identical to Person.generate_slug(), but repeated here so as not to rely on
    model code during a migration.

    Adapted from mep-django"""
    Person = apps.get_model("entities", "Person")
    Name = apps.get_model("entities", "Name")
    ContentType = apps.get_model("contenttypes", "ContentType")

    person_contenttype = ContentType.objects.get_for_model(Person)

    for person in Person.objects.all():
        # Person.__str__ method
        try:
            person_name = Name.objects.get(
                content_type=person_contenttype, object_id=person.pk, primary=True
            )
            person_str = person_name.name
        except Name.MultipleObjectsReturned:
            person_name = Name.objects.filter(
                content_type=person_contenttype, object_id=person.pk, primary=True
            ).first()
            person_str = person_name.name
        except Name.DoesNotExist:
            person_name = Name.objects.filter(
                content_type=person_contenttype, object_id=person.pk
            ).first()
            person_str = person_name.name if person_name else str(person)

        # Person.generate_slug method
        person.slug = slugify(unidecode(person_str))
        dupe_slugs = (
            Person.objects.filter(slug__startswith=person.slug)
            .exclude(pk=person.pk)
            .order_by("slug")
            .values_list("slug", flat=True)
        )
        if dupe_slugs.count() and person.slug in dupe_slugs:
            # if not unique, add a number
            prefix = "%s-" % person.slug
            # get all the endings attached to this slug (i.e. unclear-##)
            suffixes = [
                slug[len(prefix) :] for slug in dupe_slugs if slug.startswith(prefix)
            ]
            # get the largest numeric suffix
            values = [int(num) for num in suffixes if num.isnumeric()]
            slug_count = max(values) if values else 1
            # use the next number for the current slug
            person.slug = "%s-%s" % (person.slug, slug_count + 1)
        person.save()


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0022_event_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Short, durable, unique identifier for use in URLs. Save and continue editing to have a new slug autogenerated. Editing will change the public, citable URL for this person.",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="PastPersonSlug",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="past_slugs",
                        to="entities.person",
                    ),
                ),
            ],
        ),
        migrations.RunPython(populate_slugs, reverse_code=migrations.RunPython.noop),
    ]
