# Generated by Django 3.2.23 on 2024-06-07 17:12

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0024_place_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="date",
            field=models.CharField(
                blank=True,
                help_text="Manual override for automatically generated date range of this person's activity. Convert to Julian before 1582, Gregorian after 1582. \nUse YYYY, YYYY-MM, YYYY-MM-DD format or YYYY-MM-DD/YYYY-MM-DD for date ranges.",
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile(
                            "^\\d{3,4}(-[01]\\d(-[0-3]\\d)?)?(/\\d{3,4}(-[01]\\d(-[0-3]\\d)?)?)?$"
                        )
                    )
                ],
                verbose_name="CE date range override",
            ),
        ),
    ]
