# Generated by Django 3.2.23 on 2025-01-23 17:51

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taggit", "0003_taggeditem_add_unique_index"),
        ("entities", "0025_person_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                related_name="tagged_person",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
