# Generated by Django 3.2.23 on 2025-01-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0026_person_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="placeplacerelationtype",
            name="converse_name",
            field=models.CharField(
                blank=True,
                help_text="The converse of the relationship, for example, 'City' when Name is 'Neighborhood'. May leave blank if the converse is identical (for example, 'Possibly the same as').",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="placeplacerelationtype",
            name="converse_name_ar",
            field=models.CharField(
                blank=True,
                help_text="The converse of the relationship, for example, 'City' when Name is 'Neighborhood'. May leave blank if the converse is identical (for example, 'Possibly the same as').",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="placeplacerelationtype",
            name="converse_name_en",
            field=models.CharField(
                blank=True,
                help_text="The converse of the relationship, for example, 'City' when Name is 'Neighborhood'. May leave blank if the converse is identical (for example, 'Possibly the same as').",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="placeplacerelationtype",
            name="converse_name_he",
            field=models.CharField(
                blank=True,
                help_text="The converse of the relationship, for example, 'City' when Name is 'Neighborhood'. May leave blank if the converse is identical (for example, 'Possibly the same as').",
                max_length=255,
                null=True,
            ),
        ),
    ]
