# Generated by Django 3.2.23 on 2025-04-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0028_place_is_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="persondocumentrelation",
            name="uncertain",
            field=models.BooleanField(
                default=False,
                help_text="True if this association is inferred or uncertain. Please also include reasoning in the notes.",
            ),
        ),
    ]
