# Generated by Django 3.2.23 on 2025-04-10 21:46

from django.db import migrations


def populate_uncertain_relations(apps, schema_editor):
    PersonDocumentRelation = apps.get_model("entities", "PersonDocumentRelation")
    PersonDocumentRelationType = apps.get_model(
        "entities", "PersonDocumentRelationType"
    )
    for relation in PersonDocumentRelation.objects.filter(
        type__name__icontains="Possibl"
    ):
        uncertain_name = (
            relation.type.name.replace("Possible ", "")
            .replace("Possibly ", "")
            .capitalize()
        )
        pdr_type, _ = PersonDocumentRelationType.objects.get_or_create(
            name=uncertain_name
        )
        relation.type = pdr_type
        relation.uncertain = True
        relation.save()


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0030_update_person_slugs"),
    ]

    operations = [
        migrations.RunPython(populate_uncertain_relations, migrations.RunPython.noop)
    ]
