# Generated by Django 3.2.23 on 2025-06-12 17:45

from django.db import migrations, models


def migrate_role_to_roles(apps, schema_editor):
    # migrate Person.role ForeignKey field values to ManyToManyField
    Person = apps.get_model("entities", "Person")
    # use role_id to avoid unnecessary db join
    for person in Person.objects.exclude(role_id=None):
        person.roles.add(person.role_id)


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0031_populate_persondocumentrelation_uncertain"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="roles",
            field=models.ManyToManyField(
                blank=True,
                help_text="This person's social roles.",
                to="entities.PersonRole",
                verbose_name="Roles",
            ),
        ),
        migrations.RunPython(migrate_role_to_roles, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="person",
            name="role",
        ),
    ]
