# Generated by Django 5.2.4 on 2025-08-19 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0033_region"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="region",
            options={
                "verbose_name": "Geographic area",
                "verbose_name_plural": "Geographic areas",
            },
        ),
        migrations.AlterField(
            model_name="place",
            name="containing_region",
            field=models.ForeignKey(
                blank=True,
                help_text="The geographic area containing this place. For internal use and CSV exports only.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="entities.region",
                verbose_name="Geographic area",
            ),
        ),
    ]
