# Generated by Django 5.2.4 on 2025-10-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0034_alter_region_options_alter_place_containing_region"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentplacerelationtype",
            options={
                "ordering": ("order",),
                "verbose_name": "Document-Place relationship",
                "verbose_name_plural": "Document-Place relationships",
            },
        ),
        migrations.AlterModelOptions(
            name="persondocumentrelationtype",
            options={
                "ordering": ("order",),
                "verbose_name": "Person-Document relationship",
                "verbose_name_plural": "Person-Document relationships",
            },
        ),
        migrations.AddField(
            model_name="documentplacerelationtype",
            name="order",
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="persondocumentrelationtype",
            name="order",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
