# Generated by Django 5.2.6 on 2026-04-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0035_alter_documentplacerelationtype_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="A description that will appear on the public Person page.",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="description_ar",
            field=models.TextField(
                blank=True,
                help_text="A description that will appear on the public Person page.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="description_en",
            field=models.TextField(
                blank=True,
                help_text="A description that will appear on the public Person page.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="description_he",
            field=models.TextField(
                blank=True,
                help_text="A description that will appear on the public Person page.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="has_page",
            field=models.BooleanField(
                default=True,
                help_text="Check box if this person should have a dedicated, public Person page on the PGP. If checked, please draft a public description below.",
                verbose_name="Person page",
            ),
        ),
    ]
