# Generated by Django 3.1.6 on 2021-04-05 13:20

from django.conf import settings
from django.db import migrations


def create_team_user(apps, schema_editor):
    """Creates a generic Geniza Lab user account for associating with data and
    events that don't belong to a specific person."""
    User = apps.get_model("auth", "User")
    User.objects.get_or_create(
        username=settings.TEAM_USERNAME,
        first_name="Geniza Lab",
        last_name="team",
        is_staff=False,
        is_active=False,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_document_fragment_permissions"),
    ]

    operations = [
        migrations.RunPython(create_team_user, reverse_code=migrations.RunPython.noop),
    ]
