# Generated by Django 3.2.13 on 2022-09-20 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("footnotes", "0020_alter_footnote_content"),
        ("common", "0005_create_team_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "github_coauthor",
                    models.CharField(
                        blank=True,
                        help_text="Co-author information to credit your contributions\n        in GitHub Backups.\n        See <a href='https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors'>GitHub documentation</a>\n        for instructions on finding or setting yours.",
                        max_length=255,
                        verbose_name="GitHub Co-Author Email",
                    ),
                ),
                (
                    "creator",
                    models.OneToOneField(
                        blank=True,
                        help_text="Author record for scholarship records, for users who are also authors",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="footnotes.creator",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
