# Generated by Django 3.2.9 on 2022-01-03 21:28

from django.contrib.auth.management import create_permissions
from django.db import migrations

CONTENT_ADMIN = "Content Admin"
# additional new permissions for content admin
content_admin_perms = ["delete_logentry", "change_logentry"]


def update_content_editor_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    # make sure permissions are created before loading the fixture
    # which references them
    # (when running migrations all at once, permissions may not yet exist)
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=0)
        app_config.models_module = None

    # update content admin group; add to content edit permissions
    permissions = []
    admin_group = Group.objects.get(name=CONTENT_ADMIN)
    for codename in content_admin_perms:
        permissions.append(Permission.objects.get(codename=codename))
    admin_group.permissions.add(*permissions)


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_create_team_user"),
    ]

    operations = [
        migrations.RunPython(
            update_content_editor_groups, reverse_code=migrations.RunPython.noop
        )
    ]
