# Generated by Django 3.2.23 on 2024-02-29 18:02

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0008_preload_github_coauthors"),
    ]

    operations = [
        UnaccentExtension(),
    ]
