name: dbdocs

on:
  push:
    branches:
      - main
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main]

env:
  NODE_VERSION: 16
  DB_NAME: geniza
  DB_USER: geniza
  DB_PASSWORD: geniza
  DJANGO_ENV: test

jobs:
  publish-dbdocs:
    name: Publish dbdocs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # Node is required to use dbdocs
      - name: Setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ env.NODE_VERSION }}
      # dbdocs is pinned to 0.8 until django-dbml supports 0.9+
      - name: Install dbdocs
        run: npm install -g dbdocs@0.8
      - name: Check dbdocs
        run: dbdocs
      # Python version to use is stored in the .python-version file, which is the
      # convention for pyenv: https://github.com/pyenv/pyenv
      - name: Get Python version
        run: echo "PYTHON_VERSION=$(cat .python-version)" >> $GITHUB_ENV
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: pip install -e '.[test]'
      - name: Setup local_settings.py
        run: python -c "import uuid; print('SECRET_KEY = \'%s\'' % uuid.uuid4())" >> geniza/settings/local_settings.py

      # Build and publish dbdocs
      - name: Generate DBML
        run: python manage.py dbml corpus common footnotes djiffy contenttypes admin auth entities > geniza.dbml
      - name: Push to dbdocs
        env:
          DBDOCS_TOKEN: ${{ secrets.DBDOCS_TOKEN }}
        run: dbdocs build geniza.dbml --project geniza
