name: tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Configure local settings
      run: cp scripts/local_settings.py.sample scripts/local_settings.py

      # Ignoring testing for now while prototyping
    - name: Run tests
      # run: python -m pytest
      run: echo "Hello World"
